### ISSUE TITLE
How to Add Firmware to your repo?

### ISSUE THREAD

**Issue by dillera** [AdamWill/baytrail-m#10]
Looking to better support the Acer BayTrails.

I found this:

http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/tree/intel

But I have no idea how to get that into your firmware folder here, and from there build a new kernel. I'm building a fresh rawhide system to attempt this, but for now I'm trying to track down Acer specific stuff for your repo.

**Comment by AdamWill** [comment]
Well, that firmware is already included in Fedora and Fedlet as the package 'linux-firmware'. If there's a file that was only very recently added it may not be in the Fedora package yet, but it's updated pretty frequently. Our current F23 package is a 2015-07-15 snapshot.

Usually if your problem is a missing firmware file, the driver will log it in the journal.

**Comment by dillera** [comment]
Ok, np, it's not a new file I found, just confused on my end.
